# Generated by Django 4.2.1 on 2023-05-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='studenttest.test')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='studenttest.exercise'),
            preserve_default=False,
        ),
    ]
