# Generated by Django 4.2.1 on 2023-05-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0002_remove_submission_test_test_due_date_test_is_graded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceExercise',
            fields=[
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studenttest.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studenttest.submission')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('O', 'Open question'), ('M', 'Multiple choice question'), ('C', 'Coding question')], default=None, max_length=1, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='test_%Y%m%d/'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('multiple_choice_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='studenttest.multiplechoiceexercise')),
            ],
        ),
    ]
