# Generated by Django 4.2.1 on 2023-05-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0005_remove_textanswer_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
