# Generated by Django 4.2.1 on 2023-05-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0007_exercise_expected_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='signed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='expected_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('O', 'Domanda aperta'), ('M', 'Scelta multipla'), ('C', 'Codice')], max_length=1, null=True),
        ),
    ]
