# Generated by Django 4.2.1 on 2023-05-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0010_remove_exercise_signed_userexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('O', 'Domanda aperta'), ('M', 'Scelta multipla'), ('C', 'Codice'), ('D', 'Diagramma di flusso')], max_length=1, null=True),
        ),
    ]
