# Generated by Django 4.2.1 on 2023-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0011_alter_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
