# Generated by Django 4.2.1 on 2023-05-23 12:06

from django.db import migrations, models
import studenttest.models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0012_exercise_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=studenttest.models.user_directory_path),
        ),
    ]
