# Generated by Django 4.2.1 on 2023-06-01 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0014_test_visible_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
