# Generated by Django 4.2.1 on 2023-05-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0004_alter_exercise_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='multiple_choice_exercise',
        ),
        migrations.AddField(
            model_name='choice',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='studenttest.exercise'),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studenttest.choice'),
        ),
        migrations.AddField(
            model_name='submission',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MultipleChoiceExercise',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
