# Generated by Django 4.2.1 on 2023-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0006_test_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='expected_answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
