# Generated by Django 4.2.1 on 2023-05-12 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studenttest', '0008_exercise_signed_alter_exercise_expected_answer_and_more'),
    ]

    operations = [
    ]
