# Generated by Django 4.2.1 on 2023-05-29 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studenttest', '0013_alter_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
