# Generated by Django 5.2.17 on 2026-08-25 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenttest', '0019_alter_enrollment_course_alter_enrollment_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique_submission_per_user_exercise'),
        ),
    ]
